<?php
$first = 15/9;
echo "This is the result of dividing 15 by 9: $first <br>";
$firstceil = ceil($first);
echo "This is the result of dividing 15 by 9 and applying ceil: $firstceil <br>";
$firstfloor = floor($first);
echo "This is the result of dividing 15 by 9 and applying floor: $firstfloor <br>";
echo "ceil rounds up to the next highest integer and floor rounds down to the next lowest integer <br>";
$decno = 35;
$dectobin = decbin($decno);
echo "The decimal number is $decno and converted to binary it is $dectobin <br>";
$binno = 1111;
$bintodec = bindec($binno);
echo "The binary number is $binno and converted to decimal it is $bintodec <br>";
$dectohex = dechex($decno);
echo "The decimal number is $decno and converted to hex it is $dectohex <br>";
$hexno = 'A6';
$hextodec = hexdec($hexno);
echo "The hexadecimal number is $hexno and converted to decimal it is $hextodec <br>"; 
$bintohex = bin2hex($binno);
echo "The binary number is $binno and converted to hexadecimal it is $bintohex <br>";
echo "Note that it is doing a digit by digit conversion and a binary 1 is represented by 31 in hex when you look at the charts <br>";
$packrslt = pack('H*',$bintohex);
echo "This shows the result of using pack on $bintohex, you get $packrslt <br>";
$charstr = "Hello World";
$convertbin2hex = bin2hex($charstr);
echo "This shows using bin2hex on a string of characters $charstr, you get $convertbin2hex <br>";
$convertpack = pack("H*",$convertbin2hex);
echo "This shows converting back to the characters, $convertpack <br>";
$powerof3 = pow(4,3);
echo "This shows 4 raised to the third power, $powerof3 <br>";
$numtoround = 34.167;
$numrounded = round($numtoround);
echo "This shows rounding $numtoround to a whole number and gives $numrounded <br>";
$numtoround1 = 34.567;
$numrounded = round($numtoround1);
echo "This shows rounding $numtoround1 to a whole number and gives $numrounded <br>";
$numrounded2 = round($numtoround,2);
echo "This shows rounding $numtoround to two decimal places and gives $numrounded2 <br>";
?>
